language: node_js
node_js: node
cache: yarn
jobs:
  include:
    - stage: Test
      install: yarn install --frozen-lockfile
      before_script: yarn build
      script:
        - yarn test
        - yarn size
